2.3.0
conda-forge/flask-caching-feedstock pull request #24
Opened 2024-11-05 13:21 UTC by HeavyTony2

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2024-11-05 13:22 UTC, HeavyTony2 commented
@conda-forge-admin, please rerender

2024-11-05 13:23 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found it was in an excellent condition.
I do have some suggestions for making it better though...


For **recipe/meta.yaml**:

 * No valid build backend found for Python recipe for package `flask-caching` using `pip`. Python recipes using `pip` need to explicitly specify a build backend in the `host` section. If your recipe has built with only `pip` in the `host` section in the past, you likely should add `setuptools` to the `host` section of your recipe.

2024-11-05 13:41 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found it was in an excellent condition.

2024-11-13 17:42 UTC, HeavyTony2 commented
@conda-forge-admin, please rerender

2024-11-13 17:43 UTC, HeavyTony2 commented
ping @ap--

2024-11-13 17:46 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipe/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `run` section of the recipe, you should usually use `python >={{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

2024-11-16 21:25 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found it was in an excellent condition.

2024-11-16 21:37 UTC, HeavyTony2 commented
@conda-forge-admin, please rerender

2024-11-19 17:35 UTC, ap-- requested changes
Thank you for your contribution @HeavyTony2 and @rxm7706 

Please commit the small suggestion and then this is good to be merged.

2024-11-19 17:35 UTC, ap-- commented on recipe/meta.yaml
> +  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flask_caching-{{ version }}.tar.gz
Please make this small modification:

```suggestion
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
```

2024-11-19 17:44 UTC, merged